sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libasound2-dev
            - libpthread-stubs0-dev
      env: COMPILER=g++-5
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - libasound2-dev
            - libpthread-stubs0-dev
      env: 
      - COMPILER=clang++
      - CPPFLAGS="-I /usr/include/c++/v1"
    - os: osx
      compiler: clang
      env: COMPILER=clang++
      # GCC is linked to clang, so we don't need to compile twice for same compiler/platform

before_install:
  # Mac OS X images originally ship with CMake 3.0 and OpenSSL 0.9
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade cmake  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade openssl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link openssl --force; fi # Force to use homebrew version

before_script:
  - echo $TRAVIS_OS_NAME
  - cmake --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DTEST_OUTPUT_CONSOLE=ON ../
  
script: make

after_script:
  - cd build
  - chmod +x test/Tests
  - test/Tests

before_deploy:
  - ls ./
  - mv build/OHMCommStandalone build/OHMCommStandalone-$TRAVIS_OS_NAME-$TRAVIS_TAG

deploy:
  provider: releases
  api_key: "eCpBRcWXtxWlRBxGVQFwMq+zR5ga4/TwZZV1W5pgJd1mT6sECTFaYr5Z3T7MOoSWkBBYFQ56ulIi4rMrcoN1WH7kbqX6RwfwYRm3LakqsLD9iRwLXzLNNke2RAAC2Z7UA8GgFaVtVHJxHj4DVLMSva9PqS2K3F9xQmiTDKp4LuU="
  file-glob: true
  file: "build/OHMCommStandalone-*"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
