os:
  - linux
  - osx

language: cpp
compiler: 
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc # GCC is linked to clang, so we don't need to compile twice for same compiler/platform

before_script:
  - echo $TRAVIS_OS_NAME
  # LINUX
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq > /dev/null; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y -q cmake libasound2-dev; fi
  #OSX
  # - gcc is linked to clang, which is in appropriate version
  - mkdir build
  - cd build
  - cmake -DTEST_OUTPUT_CONSOLE=ON ../
  
script: make -j2

after_script:
  - cd build
  - chmod +x test/Tests
  - test/Tests

before_deploy:
  - ls ./
  - mv build/OHMComm build/OHMComm-$TRAVIS_OS_NAME-$TRAVIS_TAG

deploy:
  provider: releases
  api_key: "eCpBRcWXtxWlRBxGVQFwMq+zR5ga4/TwZZV1W5pgJd1mT6sECTFaYr5Z3T7MOoSWkBBYFQ56ulIi4rMrcoN1WH7kbqX6RwfwYRm3LakqsLD9iRwLXzLNNke2RAAC2Z7UA8GgFaVtVHJxHj4DVLMSva9PqS2K3F9xQmiTDKp4LuU="
  file-glob: true
  file: "build/OHMComm-*"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
